import React from 'react';
import '../styles/HomePage.css';
// Import images generated by DALL-E or any other source
import TradingBotImage from '../assets/trading-bot.png';
import AnalyticsImage from '../assets/analytics.png';
import SecurityImage from '../assets/security.png';

function HomePage() {
  return (
    <div className="home-page">
      {/* Hero Section */}
      <section
        className="hero-section"
        style={{ backgroundImage: `url(${TradingBotImage})` }}
      >
        <h1>Meet your new crypto trading bots</h1>
        <p>
          A platform offering a strategic, automated, and secure approach to
          amplify your trading performance.
        </p>
        <button className="button-primary">Start Trading</button>
      </section>

      {/* Features Section */}
      <section className="features-section">
        <div className="feature-card">
          <img src={AnalyticsImage} alt="Advanced Analytics" />
          <h2>Advanced Analytics</h2>
          <p>
            Utilize our analytics tools to make informed decisions and stay
            ahead in the market.
          </p>
        </div>
        <div className="feature-card">
          <img src={SecurityImage} alt="Secure Transactions" />
          <h2>Secure Transactions</h2>
          <p>
            Trade with confidence knowing your investments are safeguarded with
            the latest security measures.
          </p>
        </div>
        {/* Add additional feature cards as needed */}
      </section>

      {/* Testimonials Section */}
      <section className="testimonials-section">
        <h2>What Our Traders Say</h2>
        <div className="testimonial">
          <p>
            “Qtrading transformed my approach to trading. Intuitive tools and
            analytics have been a game-changer for me.”
          </p>
          <cite>— Alex Mercer, Day Trader</cite>
        </div>
        {/* Additional testimonials */}
      </section>

      {/* Market Tools Section */}
      <section className="market-tools-section">
        <h2>The Right Tools for Every Kind of Market</h2>
        {/* Add cards for each market tool */}
      </section>

      {/* Call to Action Section */}
      <section className="call-to-action-section">
        <h2>Join the Qtrading Community</h2>
        <p>
          Explore a realm of trading possibilities. Register now and
          revolutionize your trading experience.
        </p>
        <button className="button-secondary">Sign Up Now</button>
      </section>

      {/* Footer */}
      <footer className="site-footer">
        <p>Start Trading on Qtrading Today</p>
        <button className="button-footer">Start Now</button>
      </footer>
    </div>
  );
}

export default HomePage;
